# Example configuration for translation task

llm:
  model: gpt-4o-mini
  temperature: 0.3
  max_tokens: 200

processing:
  mode: async
  batch_size: 10

prompt: |
  Translate the following word to Spanish, French, and German.
  Word: {word}

  Return ONLY valid JSON in this format:
  {"es": "spanish", "fr": "french", "de": "german"}
